services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: fj-frontend:latest
    container_name: fj-frontend
    hostname: fj-frontend
    env_file:
      - frontend.env
    ports:
      - "3900:80"
    networks:
      - fj_network
    restart: unless-stopped

networks:
  fj_network:
    external: true
    name: frankenjet
