services:
  backend:
    image: fj-backend:latest
    container_name: fj-backend
    hostname: fj-backend
    env_file:
      - backend.env
    networks:
      - fj_network
    restart: unless-stopped

  frontend:
    image: fj-frontend:latest
    container_name: fj-frontend
    hostname: fj-frontend
    depends_on:
      - backend
    env_file:
      - frontend.env
    networks:
      - fj_network
    restart: unless-stopped

networks:
  fj_network:
    external: true
    name: frankenjet
