services:
  notifications:
    image: fj-bot:latest
    container_name: fj-bot
    hostname: bot
    env_file:
      - bot.env
    networks:
      - network
    restart: unless-stopped

  backend:
    image: fj-backend:latest
    container_name: fj-backend
    hostname: backend
    depends_on:
      - notifications
    env_file:
      - backend.env
    ports:
      - "8000:8000"
    networks:
      - network
    restart: unless-stopped

  frontend:
    image: fj-frontend:latest
    container_name: fj-frontend
    hostname: frontend
    depends_on:
      - backend
    env_file:
      - frontend.env
    ports:
      - "3000:3000"
    networks:
      - network
    restart: unless-stopped

networks:
  network:
