services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: fj-backend:latest
    container_name: fj-backend
    hostname: fj-backend
    environment:
      - APP_MODE=production
    env_file:
      - backend.env
    ports:
      - "8900:8000"
    networks:
      - fj_network
    restart: unless-stopped

networks:
  fj_network:
    external: true
    name: frankenjet
