<template>
  <v-container>
    <v-card>
      <v-card-title>Title</v-card-title>
      <v-card-text>
        <div>
          Context
        </div>
      </v-card-text>
    </v-card>
  </v-container>
</template>
