# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectorizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vectorizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vectorizer.proto\x12\nvectorizer\" \n\x10\x45mbedTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11\x45mbedTextResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32]\n\x11VectorizerService\x12H\n\tEmbedText\x12\x1c.vectorizer.EmbedTextRequest\x1a\x1d.vectorizer.EmbedTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectorizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDTEXTREQUEST']._serialized_start=32
  _globals['_EMBEDTEXTREQUEST']._serialized_end=64
  _globals['_EMBEDTEXTRESPONSE']._serialized_start=66
  _globals['_EMBEDTEXTRESPONSE']._serialized_end=104
  _globals['_VECTORIZERSERVICE']._serialized_start=106
  _globals['_VECTORIZERSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
