# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectorizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vectorizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vectorizer.proto\x12\nvectorizer\" \n\x10\x45mbedTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11\x45mbedTextResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"&\n\x15\x45mbedTextBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"I\n\x16\x45mbedTextBatchResponse\x12/\n\nembeddings\x18\x01 \x03(\x0b\x32\x1b.vectorizer.EmbeddingResult\"$\n\x0f\x45mbeddingResult\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\xb6\x01\n\x11VectorizerService\x12H\n\tEmbedText\x12\x1c.vectorizer.EmbedTextRequest\x1a\x1d.vectorizer.EmbedTextResponse\x12W\n\x0e\x45mbedTextBatch\x12!.vectorizer.EmbedTextBatchRequest\x1a\".vectorizer.EmbedTextBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectorizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDTEXTREQUEST']._serialized_start=32
  _globals['_EMBEDTEXTREQUEST']._serialized_end=64
  _globals['_EMBEDTEXTRESPONSE']._serialized_start=66
  _globals['_EMBEDTEXTRESPONSE']._serialized_end=104
  _globals['_EMBEDTEXTBATCHREQUEST']._serialized_start=106
  _globals['_EMBEDTEXTBATCHREQUEST']._serialized_end=144
  _globals['_EMBEDTEXTBATCHRESPONSE']._serialized_start=146
  _globals['_EMBEDTEXTBATCHRESPONSE']._serialized_end=219
  _globals['_EMBEDDINGRESULT']._serialized_start=221
  _globals['_EMBEDDINGRESULT']._serialized_end=257
  _globals['_VECTORIZERSERVICE']._serialized_start=260
  _globals['_VECTORIZERSERVICE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
